#ifndef MESSAGEMANAGER_GLOBAL_H
#define MESSAGEMANAGER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MESSAGEMANAGER_LIBRARY)
#  define MESSAGEMANAGERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define MESSAGEMANAGERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // MESSAGEMANAGER_GLOBAL_H
