#ifndef COMMANDMANAGER_GLOBAL_H
#define COMMANDMANAGER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(COMMANDMANAGER_LIBRARY)
#  define MESSAGEMANAGERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define MESSAGEMANAGERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // COMMANDMANAGER_GLOBAL_H
