#ifndef AUDIODEVICE_GLOBAL_H
#define AUDIODEVICE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(AUDIODEVICE_LIBRARY)
#  define AUDIODEVICESHARED_EXPORT Q_DECL_EXPORT
#else
#  define AUDIODEVICESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // AUDIODEVICE_GLOBAL_H
